name: Build macOS

on:
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
      - name: Install deps
        run: flutter pub get
      - name: Build macOS release
        run: flutter build macos --release
      - name: Package built app
        run: |
          mkdir -p artifacts
          APP_PATH=build/macos/Build/Products/Release/macos/Runner.app
          if [ -d "$APP_PATH" ]; then
            cd build/macos/Build/Products/Release
            zip -r "../../../../artifacts/mixzer_macos_release.zip" Runner.app
            cd -
          else
            echo "Built app not found at $APP_PATH"
            exit 1
          fi
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mixzer_macos_release
          path: artifacts/mixzer_macos_release.zip
