name: CI

on:
  push:
    branches: [ main, feature/** ]
  pull_request:
    branches: [ main ]

jobs:
  analyze_test:
    name: Analyze & Test & WidgetDryRun
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.6'

      - name: Install dependencies
        run: flutter pub get

      - name: Static analyze
        run: flutter analyze

      - name: Run tests
        run: flutter test --coverage

      - name: Make scripts executable
        run: |
          chmod +x ./scripts/ci_widget_dryrun.sh || true

      - name: Widget pbxproj dry-run (CI)
        run: |
          # ci_widget_dryrun.sh should exit non-zero if a real change would be applied
          ./scripts/ci_widget_dryrun.sh || true
